name: Publish Docker image

on:
  push:
    branches:
      - main  # Запуск workflow при пуше в ветку main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write
      # включаем необходимые права доступа

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Обновляем версию до последней доступной

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Настраиваем Docker Buildx

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Make the Docker image public
      run: |
        gh api \
          -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          "/user/packages/container/${{ github.repository }}/visibility" \
          -f visibility=public \
          --silent
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}